/**
 * The full 2027 fixture calendar, day by day.
 *
 * Every event is generated by `buildFullSchedule()` from the season structure,
 * so the page cannot drift from the capacity engine — and it says so, by
 * showing whether the generated schedule still reconciles with what the
 * structure requires.
 */

import { createFileRoute, Link } from "@tanstack/react-router";
import { PageShell } from "@/components/layout/PageShell";
import { useState, useMemo } from "react";
import {
  Disc3,
  CalendarDays,
  Filter,
  CheckCircle2,
  AlertTriangle,
  Radio,
  Info,
  RotateCcw,
  MapPin,
} from "lucide-react";
import {
  scheduleFor,
  totalsFor,
  SEASON_CALENDAR,
  NATIONAL_ZONES,
  WINDOWS_PER_HOUSE,
  TOTAL_BANDS,
  TOTAL_HOUSES,
  COMPETITION_WEEKENDS,
  IPL_WINDOW,
  RELEASE_SCHEDULE,
  RELEASE_TOTALS,
  CAMPUS_VENUE_LABEL,
  type EventKind,
  type ScheduledEvent,
} from "@/data/national-season";
import { SeasonSwitch } from "@/components/SeasonSwitch";
import { zonesForSeason, type SeasonId } from "@/data/season-plan";
import { FORMAT_MIX } from "@/data/show-formats";
import {
  POST_SEASON,
  POST_SEASON_TOTALS,
  POST_STAGES,
  CLOSING_BLOCKS,
  LADDER,
  QUALIFIERS_PER_ZONE,
} from "@/data/post-season";

export const Route = createFileRoute("/calendar")({
  head: () => ({
    meta: [
      { title: "2027 Fixture Calendar — Kalakshetra" },
      {
        name: "description",
        content:
          "The complete regular season, day by day: every night across all five regional leagues from 31 December to 12 June, filterable by zone, house, band and night type.",
      },
    ],
  }),
  component: CalendarPage,
});

const KIND_META: Record<EventKind, { label: string; chip: string; dot: string }> = {
  commercial: {
    label: "Commercial",
    chip: "border-emerald-500/40 bg-emerald-500/10 text-emerald-300",
    dot: "bg-emerald-400",
  },
  campus: {
    label: "Campus",
    chip: "border-cyan-500/40 bg-cyan-500/10 text-cyan-300",
    dot: "bg-cyan-400",
  },
  cross: {
    label: "Cross night",
    chip: "border-amber-500/40 bg-amber-500/10 text-amber-300",
    dot: "bg-amber-400",
  },
  house: {
    label: "House night",
    chip: "border-sky-500/40 bg-sky-500/10 text-sky-300",
    dot: "bg-sky-400",
  },
  festival: {
    label: "Festival",
    chip: "border-violet-500/40 bg-violet-500/10 text-violet-300",
    dot: "bg-violet-400",
  },
  corporate: {
    label: "Corporate",
    chip: "border-slate-500/40 bg-slate-500/10 text-slate-300",
    dot: "bg-slate-400",
  },
  // NOTE: corporate is intentionally absent from KIND_FILTERS below — those
  // nights hold a week but carry no published date.
  launch: {
    label: "League launch",
    chip: "border-amber-500/50 bg-amber-500/15 text-amber-200",
    dot: "bg-amber-400",
  },
  celebrity: {
    label: "Celebrity",
    chip: "border-pink-500/45 bg-pink-500/10 text-pink-300",
    dot: "bg-pink-400",
  }
};

/** Dec is here because the season opens on New Year's Eve, week 1's Thursday. */
const MONTHS = ["all", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun"];

function Select({
  label,
  value,
  options,
  onChange,
}: {
  label: string;
  value: string;
  options: { id: string; label: string }[];
  onChange: (v: string) => void;
}) {
  return (
    <div className="space-y-1 min-w-0">
      <label className="text-[10px] uppercase tracking-wider font-bold text-muted-foreground">
        {label}
      </label>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        aria-label={label}
        className="w-full rounded-md border border-border bg-background/70 px-2 py-1.5 text-xs font-semibold text-white focus:border-primary/60 focus:outline-none cursor-pointer"
      >
        {options.map((o) => (
          <option key={o.id} value={o.id} className="bg-background text-white">
            {o.label}
          </option>
        ))}
      </select>
    </div>
  );
}

/**
 * July to December. Nobody is named — every side is a slot, so the bracket
 * describes how a band arrives at a night without inventing who won it.
 */
function ChampionshipView({
  stage,
  setStage,
}: {
  stage: string;
  setStage: (v: string) => void;
}) {
  const filtered = useMemo(
    () => (stage === "all" ? POST_SEASON : POST_SEASON.filter((e) => e.stage === stage)),
    [stage],
  );

  const grouped = useMemo(() => {
    const byWeekend = new Map<string, typeof POST_SEASON>();
    filtered.forEach((e) => {
      if (!byWeekend.has(e.weekendLabel)) byWeekend.set(e.weekendLabel, []);
      byWeekend.get(e.weekendLabel)!.push(e);
    });
    return [...byWeekend.entries()];
  }, [filtered]);

  return (
    <div className="space-y-6">
      <div className="bpl-card p-4 border border-primary/25 bg-primary/5 flex gap-3">
        <Info size={15} className="text-primary-glow shrink-0 mt-0.5" />
        <p className="text-[11px] text-muted-foreground leading-relaxed">
          <span className="font-semibold text-white">Nobody is named here, on purpose.</span> Every
          side is a slot — <span className="text-white">AP/TS #3</span>,{" "}
          <span className="text-white">Group B winner</span>,{" "}
          <span className="text-white">QF2 winner</span>,{" "}
          <span className="text-white">Rank 2</span>. The bracket says how a band arrives at a night,
          never who it is. Putting invented names against dated fixtures would publish a fabricated
          result for real acts.
        </p>
      </div>

      {/* Ladder */}
      <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">
        {LADDER.map((l, i) => (
          <div
            key={l.stage}
            className={`rounded-lg border p-3 ${
              i === LADDER.length - 1
                ? "border-rose-500/40 bg-rose-500/5"
                : "border-border/60 bg-surface/40"
            }`}
          >
            <p className="text-2xl font-display font-extrabold text-primary-glow tabular-nums">
              {l.bands}
            </p>
            <p className="text-[10px] font-bold text-white uppercase tracking-wider mt-0.5">
              {l.stage}
            </p>
            <p className="text-[10px] text-muted-foreground leading-snug mt-1">{l.note}</p>
          </div>
        ))}
      </div>

      {/* Stage filter */}
      <div className="rounded-xl border border-border bg-surface/30 p-3 space-y-2">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-[10px] uppercase tracking-wider font-bold text-primary-glow flex items-center gap-1.5">
            <Filter size={12} /> Stage
          </span>
          <span className="text-[11px] text-muted-foreground">
            {filtered.length} of {POST_SEASON_TOTALS.events} nights
          </span>
        </div>
        <div className="flex flex-wrap gap-1.5">
          {[
            { id: "all", name: "All stages" },
            ...POST_STAGES.map((st) => ({ id: st.id as string, name: st.name })),
          ].map((st) => (
            <button
              key={st.id}
              type="button"
              onClick={() => setStage(st.id)}
              className={`px-2.5 py-1 rounded-full border text-[11px] font-bold transition cursor-pointer ${
                stage === st.id
                  ? "border-primary/60 bg-primary/15 text-primary-glow"
                  : "border-border bg-secondary/40 text-muted-foreground hover:text-white"
              }`}
            >
              {st.name}
            </button>
          ))}
        </div>
      </div>

      {/* Stage explainers */}
      {stage === "all" && (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {POST_STAGES.map((st) => (
            <div key={st.id} className="rounded-lg border border-border/60 bg-surface/40 p-3">
              <div className="flex items-center gap-2">
                <span
                  className={`text-[9px] uppercase tracking-wider font-bold px-2 py-0.5 rounded-full border ${st.accent}`}
                >
                  {st.window}
                </span>
              </div>
              <p className="text-xs font-bold text-white mt-1.5">{st.name}</p>
              <p className="text-[10px] text-muted-foreground leading-relaxed mt-1">{st.detail}</p>
            </div>
          ))}
        </div>
      )}

      {/* Fixtures */}
      <div className="space-y-3">
        {grouped.map(([weekendLabel, evts]) => (
          <div key={weekendLabel} className="bpl-card border border-border bg-surface/30 overflow-hidden">
            <div className="flex flex-wrap items-center gap-2 px-4 py-2.5 border-b border-border/60 bg-secondary/20">
              <span className="text-xs font-bold text-white">Weekend of {weekendLabel}</span>
              <div className="flex-1" />
              <span className="text-[10px] text-muted-foreground tabular-nums">
                {evts.length} {evts.length === 1 ? "night" : "nights"}
              </span>
            </div>
            <div className="grid gap-1.5 sm:grid-cols-2 lg:grid-cols-3 p-3">
              {evts.map((e) => {
                const meta = POST_STAGES.find((st) => st.id === e.stage)!;
                return (
                  <div
                    key={e.id}
                    className="rounded-md border border-border/50 bg-surface/40 px-2.5 py-2 space-y-1"
                  >
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-[11px] font-semibold text-white leading-snug">
                        {e.sideA} <span className="text-muted-foreground">v</span> {e.sideB}
                      </p>
                      <span
                        className={`text-[8px] uppercase tracking-wider font-bold px-1.5 py-0.5 rounded border shrink-0 ${meta.accent}`}
                      >
                        {meta.name}
                      </span>
                    </div>
                    <p className="text-[10px] text-muted-foreground flex flex-wrap items-center gap-x-1.5">
                      <span>{e.dateLabel}</span>
                      <span className="opacity-40">·</span>
                      <span className="inline-flex items-center gap-0.5">
                        <MapPin size={8} />
                        {e.city}
                      </span>
                    </p>
                    <p className="text-[10px] text-muted-foreground/80 leading-snug">{e.context}</p>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Nov + Dec */}
      <div className="grid gap-4 lg:grid-cols-2">
        {CLOSING_BLOCKS.map((b) => (
          <div key={b.title} className="bpl-card p-5 border border-border bg-surface/40 space-y-3">
            <div>
              <span className="text-[10px] uppercase tracking-wider font-bold text-muted-foreground">
                {b.window}
              </span>
              <h3 className="text-sm font-bold text-white">{b.title}</h3>
            </div>
            <p className="text-[11px] text-muted-foreground leading-relaxed">{b.detail}</p>
            <ul className="space-y-1">
              {b.items.map((it) => (
                <li key={it} className="text-[10px] text-muted-foreground leading-snug flex gap-1.5">
                  <span className="opacity-50">·</span>
                  {it}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      <div
        className={`bpl-card p-4 border flex gap-3 ${
          POST_SEASON_TOTALS.reconciles
            ? "border-emerald-500/30 bg-emerald-500/5"
            : "border-rose-500/30 bg-rose-500/5"
        }`}
      >
        {POST_SEASON_TOTALS.reconciles ? (
          <CheckCircle2 size={15} className="text-emerald-400 shrink-0 mt-0.5" />
        ) : (
          <AlertTriangle size={15} className="text-rose-400 shrink-0 mt-0.5" />
        )}
        <p className="text-[11px] text-muted-foreground leading-relaxed">
          <span className="font-semibold text-emerald-200">Bracket checks out.</span>{" "}
          {POST_SEASON_TOTALS.regionalFinals} regional-final nights (five zones, every one of the{" "}
          {QUALIFIERS_PER_ZONE} qualifiers meeting the other four),{" "}
          {POST_SEASON_TOTALS.groupStage} group nights and {POST_SEASON_TOTALS.knockout} knockout
          nights — {POST_SEASON_TOTALS.events} in all, July to October. November and December carry
          no fixtures by design.
        </p>
      </div>
    </div>
  );
}

function CalendarPage() {
  const [half, setHalf] = useState<"regular" | "championship">("regular");
  const [stage, setStage] = useState<string>("all");
  // Season 1 is AP/TS alone, season 2 the national five. The page opens on
  // the launch season, because that is the one that has to be believable.
  const [season, setSeason] = useState<SeasonId>("s1");
  const schedule = useMemo(() => scheduleFor(season), [season]);
  const totals = useMemo(() => totalsFor(season), [season]);
  const seasonZones = useMemo(() => zonesForSeason(season), [season]);
  const [zone, setZone] = useState("all");
  const [house, setHouse] = useState("all");
  const [band, setBand] = useState("all");
  const [kind, setKind] = useState("all");
  const [month, setMonth] = useState("all");

  const zoneMeta = NATIONAL_ZONES.find((z) => z.slug === zone) ?? null;
  const maxHouses = zoneMeta ? zoneMeta.houses : Math.max(...NATIONAL_ZONES.map((z) => z.houses));
  const maxBands = zoneMeta
    ? zoneMeta.bandsPerHouse
    : Math.max(...NATIONAL_ZONES.map((z) => z.bandsPerHouse));

  const filtered = useMemo(
    () =>
      schedule.filter((e) => {
        // Private bookings hold a week but have no published date — putting one
        // on the calendar would assert a sale nobody has made.
        if (!e.dated) return false;
        if (zone !== "all" && e.zoneSlug !== zone) return false;
        if (house !== "all" && e.houseNumber !== Number(house)) return false;
        if (band !== "all" && !e.bands.includes(Number(band))) return false;
        if (kind !== "all" && e.kind !== kind) return false;
        if (month !== "all" && !e.dateLabel.includes(month)) return false;
        return true;
      }),
    [zone, house, band, kind, month],
  );

  /** Releases keyed by the day they land on, shown beside that day's fixtures. */
  const releasesByDay = useMemo(() => {
    const map = new Map<string, typeof RELEASE_SCHEDULE>();
    RELEASE_SCHEDULE.forEach((r) => {
      if (zone !== "all" && r.zoneSlug !== zone) return;
      if (house !== "all" && r.houseNumber !== Number(house)) return;
      if (band !== "all" && r.band !== Number(band)) return;
      if (month !== "all" && !r.dateLabel.includes(month)) return;
      if (!map.has(r.dateLabel)) map.set(r.dateLabel, []);
      map.get(r.dateLabel)!.push(r);
    });
    return map;
  }, [zone, house, band, month]);

  /**
   * Group by weekend, then by calendar day inside it.
   *
   * Releases land on fixed calendar dates — the 1st and the 16th — which very
   * often are not days the band happens to be playing. Those days still need a
   * row, or filtering to a single band renders its fixtures and silently drops
   * the three release tags that are the point of the view. So release dates
   * seed an empty day, using the same zone/house/band filter the releases
   * themselves were narrowed by.
   */
  const grouped = useMemo(() => {
    const byWeekend = new Map<number, Map<string, ScheduledEvent[]>>();
    filtered.forEach((e) => {
      if (!byWeekend.has(e.weekendIndex)) byWeekend.set(e.weekendIndex, new Map());
      const days = byWeekend.get(e.weekendIndex)!;
      if (!days.has(e.dateLabel)) days.set(e.dateLabel, []);
      days.get(e.dateLabel)!.push(e);
    });

    releasesByDay.forEach((rels, dayLabel) => {
      const wi = Math.max(0, (rels[0]?.week ?? 1) - 1);
      if (!byWeekend.has(wi)) byWeekend.set(wi, new Map());
      const days = byWeekend.get(wi)!;
      if (!days.has(dayLabel)) days.set(dayLabel, []);
    });

    // A day seeded by a release has no fixture to read a date from.
    const dayDate = (label: string) =>
      releasesByDay.get(label)?.[0]?.date.getTime() ?? 0;

    return [...byWeekend.entries()]
      .map(
        ([wi, days]) =>
          [
            wi,
            new Map(
              [...days.entries()].sort(
                (a, b) =>
                  (a[1][0]?.date.getTime() ?? dayDate(a[0])) -
                  (b[1][0]?.date.getTime() ?? dayDate(b[0])),
              ),
            ),
          ] as [number, Map<string, ScheduledEvent[]>],
      )
      .sort((a, b) => a[0] - b[0]);
  }, [filtered, releasesByDay]);

  const isDefault =
    zone === "all" && house === "all" && band === "all" && kind === "all" && month === "all";

  const reset = () => {
    setZone("all");
    setHouse("all");
    setBand("all");
    setKind("all");
    setMonth("all");
  };

  return (
    <PageShell>
      <div className="bg-background text-white min-h-screen">
        {/* HERO */}
        <section className="relative overflow-hidden border-b border-border">
          <div
            className="absolute inset-0 pointer-events-none"
            style={{
              background:
                "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(16, 185, 129, 0.16), transparent 70%)",
            }}
          />
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 pt-16 pb-10 space-y-6 text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-emerald-500/30 bg-emerald-500/10 text-emerald-300 text-xs font-semibold">
              <CalendarDays size={14} />
              <span>Season 1 · 2027 Regular Season</span>
            </div>
            <h1 className="text-4xl sm:text-5xl font-display font-extrabold tracking-tight text-white max-w-3xl mx-auto leading-tight">
              Every night of <span className="gradient-text">2027</span>
            </h1>
            <p className="text-sm text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              The complete regular season, 31 December to 12 June — all{" "}
              {totals.events} events across {seasonZones.length} regional league{seasonZones.length === 1 ? "" : "s"},{" "}
              {TOTAL_HOUSES} production houses and {TOTAL_BANDS} bands, generated from the season
              structure rather than typed out.
            </p>

            <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 pt-2 text-left">
              {[
                { v: totals.events, l: "Events", h: `${COMPETITION_WEEKENDS} weekends` },
                {
                  v: totals.commercial,
                  l: "Commercial",
                  h: `${FORMAT_MIX.commercialPerBand} per band`,
                },
                { v: totals.campus, l: "Campus", h: `${FORMAT_MIX.campusPerBand} per band` },
                { v: totals.cross, l: "Cross nights", h: "Shared stages" },
                { v: RELEASE_TOTALS.releases, l: "Song releases", h: `${RELEASE_TOTALS.perBand} per band` },
              ].map((s) => (
                <div key={s.l} className="bpl-card p-4 border border-border/80 bg-surface/60">
                  <p className="text-2xl font-display font-extrabold text-emerald-300 tabular-nums">
                    {s.v}
                  </p>
                  <p className="text-[10px] uppercase tracking-wider font-bold text-white mt-1">
                    {s.l}
                  </p>
                  <p className="text-[10px] text-muted-foreground">{s.h}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <div className="mx-auto max-w-7xl px-4 sm:px-6 py-10 space-y-6">
          {/* Which season this calendar is describing. */}
          <div className="bpl-card p-4 border border-primary/25 bg-primary/5">
            <SeasonSwitch value={season} onChange={setSeason} />
          </div>

          {/* What is deliberately not on this calendar */}
          <div className="bpl-card p-4 border border-border bg-surface/40 flex gap-3">
            <Info size={15} className="text-primary-glow shrink-0 mt-0.5" />
            <p className="text-[11px] text-muted-foreground leading-relaxed">
              <span className="font-semibold text-white">
                {totals.heldSlots} corporate bookings are held, not dated.
              </span>{" "}
              Every band&apos;s season reserves three weeks for private shows, taken from the
              Saturdays nothing else claims, so the load is planned for rather than discovered. But
              a corporate booking happens when a buyer turns up — publishing a date and a city for
              one would assert a sale nobody has made. That is why a band&apos;s season is{" "}
              {totals.appearancesPerBandAllFormats} appearances while this calendar dates{" "}
              {totals.appearancesPerBandInSeason} of them.
            </p>
          </div>

          {/* Reconciliation */}
          <div
            className={`bpl-card p-4 border flex gap-3 ${
              totals.reconciles
                ? "border-emerald-500/30 bg-emerald-500/5"
                : "border-rose-500/30 bg-rose-500/5"
            }`}
          >
            {totals.reconciles ? (
              <CheckCircle2 size={15} className="text-emerald-400 shrink-0 mt-0.5" />
            ) : (
              <AlertTriangle size={15} className="text-rose-400 shrink-0 mt-0.5" />
            )}
            <p className="text-[11px] text-muted-foreground leading-relaxed">
              {totals.reconciles ? (
                <>
                  <span className="font-semibold text-emerald-200">Schedule reconciles.</span> The{" "}
                  {totals.individual} individual fixtures and {totals.cross} cross
                  nights generated here match exactly what the{" "}
                  <Link to="/season" className="text-primary-glow font-semibold hover:underline">
                    capacity engine
                  </Link>{" "}
                  says the structure requires. Every band gets {FORMAT_MIX.commercialPerBand}{" "}
                  commercial, {FORMAT_MIX.campusPerBand} campus and {FORMAT_MIX.crossPerBand} versus
                  nights — the same {FORMAT_MIX.totalPerBand} formats in the same proportions, in
                  every zone.
                </>
              ) : (
                <span className="font-semibold text-rose-200">
                  Generated schedule does not match the structural requirement — the generator and
                  the capacity engine disagree.
                </span>
              )}
            </p>
          </div>

          {/* Half-year toggle */}
          <div className="flex flex-wrap gap-2">
            {(
              [
                { id: "regular", label: "Regular Season · Jan–Jun", n: totals.events },
                { id: "championship", label: "Championship · Jul–Dec", n: POST_SEASON_TOTALS.events },
              ] as const
            ).map((h) => (
              <button
                key={h.id}
                type="button"
                onClick={() => setHalf(h.id)}
                className={`px-4 py-2 rounded-lg border text-xs font-bold transition cursor-pointer ${
                  half === h.id
                    ? "border-primary/60 bg-primary/15 text-primary-glow"
                    : "border-border bg-secondary/40 text-muted-foreground hover:text-white hover:border-primary/40"
                }`}
              >
                {h.label}
                <span className="ml-2 opacity-70 tabular-nums">{h.n}</span>
              </button>
            ))}
          </div>

          {half === "championship" ? (
            <ChampionshipView stage={stage} setStage={setStage} />
          ) : (
            <>
          {/* Filters */}
          <div className="rounded-xl border border-primary/25 bg-primary/5 p-3 space-y-3">
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-[10px] uppercase tracking-wider font-bold text-primary-glow flex items-center gap-1.5">
                <Filter size={12} /> Filter
              </span>
              <span className="text-[11px] text-muted-foreground">
                {filtered.length} of {totals.events} events
              </span>
              <div className="flex-1" />
              {!isDefault && (
                <button
                  type="button"
                  onClick={reset}
                  className="inline-flex items-center gap-1 text-[11px] font-semibold text-muted-foreground hover:text-white transition cursor-pointer"
                >
                  <RotateCcw size={11} /> Reset
                </button>
              )}
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-2">
              <Select
                label="Zone"
                value={zone}
                options={[
                  { id: "all", label: "All zones" },
                  ...seasonZones.map((z) => ({ id: z.slug, label: z.shortName })),
                ]}
                onChange={(v) => {
                  setZone(v);
                  setHouse("all");
                  setBand("all");
                }}
              />
              <Select
                label="House"
                value={house}
                options={[
                  { id: "all", label: "All houses" },
                  ...Array.from({ length: maxHouses }, (_, i) => ({
                    id: String(i + 1),
                    label: `House ${i + 1}`,
                  })),
                ]}
                onChange={setHouse}
              />
              <Select
                label="Band"
                value={band}
                options={[
                  { id: "all", label: "All bands" },
                  ...Array.from({ length: maxBands }, (_, i) => ({
                    id: String(i + 1),
                    label: `Band ${i + 1}`,
                  })),
                ]}
                onChange={setBand}
              />
              <Select
                label="Night type"
                value={kind}
                options={[
                  { id: "all", label: "All nights" },
                  { id: "commercial", label: "Commercial" },
                  { id: "campus", label: "Campus" },
                  { id: "cross", label: "Cross night" },
                  { id: "house", label: "House night" },
                  { id: "festival", label: "Festival" },
                  { id: "launch", label: "League launch" },
                  { id: "celebrity", label: "Celebrity night" },
                ]}
                onChange={setKind}
              />
              <Select
                label="Month"
                value={month}
                options={MONTHS.map((m) => ({ id: m, label: m === "all" ? "All months" : m }))}
                onChange={setMonth}
              />
            </div>
            <div className="flex flex-wrap gap-3 pt-1">
              {(Object.keys(KIND_META) as EventKind[])
                .filter((k) => k !== "corporate")
                .map((k) => (
                  <span key={k} className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
                    <span className={`h-2 w-2 rounded-full ${KIND_META[k].dot}`} />
                    {KIND_META[k].label}
                  </span>
                ))}
              <span className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
                <Radio size={10} className="text-amber-400" /> Cricket-window weekend
              </span>
              <span className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
                <Disc3 size={10} className="text-fuchsia-400" /> Song release
              </span>
            </div>
          </div>

          {/* Weekend-by-weekend schedule */}
          {grouped.length === 0 ? (
            <div className="bpl-card p-8 border border-border bg-surface/30 text-center">
              <p className="text-sm text-muted-foreground">
                No fixtures match this filter. A two-band zone has no Band 3 or Band 4.
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {grouped.map(([weekendIndex, days]) => {
                const weekend = SEASON_CALENDAR.find((w) => w.index === weekendIndex);
                const count = [...days.values()].reduce((s, d) => s + d.length, 0);
                return (
                  <div
                    key={weekendIndex}
                    className="bpl-card border border-border bg-surface/30 overflow-hidden"
                  >
                    <div className="flex flex-wrap items-center gap-2 px-4 py-2.5 border-b border-border/60 bg-secondary/20">
                      <span className="text-[10px] uppercase tracking-wider font-bold px-2 py-0.5 rounded-full border border-primary/40 bg-primary/10 text-primary-glow">
                        Weekend {weekend?.number}
                      </span>
                      <span className="text-xs font-bold text-white">{weekend?.label}</span>
                      {weekend?.iplOverlap && (
                        <span className="inline-flex items-center gap-1 text-[9px] uppercase tracking-wider font-bold text-amber-400">
                          <Radio size={9} /> Cricket window
                        </span>
                      )}
                      <div className="flex-1" />
                      <span className="text-[10px] text-muted-foreground tabular-nums">
                        {count} {count === 1 ? "event" : "events"}
                      </span>
                    </div>

                    <div className="divide-y divide-border/40">
                      {[...days.entries()].map(([dayLabel, dayEvents]) => (
                        <div key={dayLabel} className="px-4 py-3">
                          <div className="flex flex-wrap items-center gap-2 mb-2">
                            <p className="text-[11px] font-bold text-white">{dayLabel}</p>
                            {(releasesByDay.get(dayLabel)?.length ?? 0) > 0 && (
                              <span className="inline-flex items-center gap-1 text-[9px] uppercase tracking-wider font-bold px-1.5 py-0.5 rounded border border-fuchsia-500/40 bg-fuchsia-500/10 text-fuchsia-300">
                                <Disc3 size={9} />
                                {releasesByDay.get(dayLabel)!.length} release
                                {releasesByDay.get(dayLabel)!.length === 1 ? "" : "s"}
                              </span>
                            )}
                          </div>
                          <div className="grid gap-1.5 sm:grid-cols-2 lg:grid-cols-3">
                            {dayEvents
                              .slice()
                              // A launch is five house rows on one zone bill, a
                              // festival stage-day ten band rows on one. Show the
                              // night, not the rows.
                              .filter(
                                (e, i, all) =>
                                  !e.billId || all.findIndex((x) => x.billId === e.billId) === i,
                              )
                              .sort((a, b) => (a.slot.includes("matinee") ? 0 : 1) - (b.slot.includes("matinee") ? 0 : 1))
                              .map((e) => (
                                <div
                                  key={e.id}
                                  className="flex items-start gap-2 rounded-md border border-border/50 bg-surface/40 px-2.5 py-2"
                                >
                                  <span
                                    className={`h-2 w-2 rounded-full shrink-0 mt-1.5 ${KIND_META[e.kind].dot}`}
                                  />
                                  <div className="min-w-0 flex-1">
                                    <p className="text-[11px] font-semibold text-white leading-snug">
                                      {e.zoneName} · H{e.houseNumber} ·{" "}
                                      {e.bands
                                        .map((b) => `B${b}`)
                                        .join(e.kind === "cross" ? " v " : ", ")}
                                      {!e.scored && (
                                        <span className="ml-1.5 text-[9px] uppercase tracking-wider font-bold text-sky-300">
                                          no points
                                        </span>
                                      )}
                                    </p>
                                    <p className="text-[10px] text-muted-foreground flex flex-wrap items-center gap-x-1.5">
                                      <span className="text-primary-glow font-semibold">
                                        {e.formatName}
                                      </span>
                                      <span className="opacity-40">·</span>
                                      <span>{e.slot}</span>
                                      <span className="opacity-40">·</span>
                                      <span className="inline-flex items-center gap-0.5">
                                        <MapPin size={8} />
                                        {e.city}
                                      </span>
                                    </p>
                                  </div>
                                  <span
                                    className={`text-[8px] uppercase tracking-wider font-bold px-1.5 py-0.5 rounded border shrink-0 ${KIND_META[e.kind].chip}`}
                                  >
                                    {KIND_META[e.kind].label}
                                  </span>
                                </div>
                              ))}
                          </div>

                          {(releasesByDay.get(dayLabel)?.length ?? 0) > 0 && (
                            <div className="mt-2 rounded-md border border-fuchsia-500/25 bg-fuchsia-500/5 px-2.5 py-2">
                              <p className="text-[9px] uppercase tracking-wider font-bold text-fuchsia-300 mb-1">
                                Music out today
                              </p>
                              <div className="flex flex-wrap gap-x-3 gap-y-1">
                                {releasesByDay.get(dayLabel)!.map((r) => (
                                  <span
                                    key={r.id}
                                    className="text-[10px] text-muted-foreground whitespace-nowrap"
                                  >
                                    <span className="text-white font-semibold">
                                      {r.zoneName} · H{r.houseNumber} · B{r.band}
                                    </span>{" "}
                                    — {r.label}
                                  </span>
                                ))}
                              </div>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          )}

            </>
          )}

          {/* Footnote — describes the regular-season list only */}
          {half === "regular" && (
          <div className="bpl-card p-5 border border-border bg-surface/30 flex gap-3">
            <Info size={15} className="text-primary-glow shrink-0 mt-0.5" />
            <div className="space-y-2">
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                <span className="font-semibold text-white">What this is.</span> A structurally valid
                schedule: every house gets its {WINDOWS_PER_HOUSE} weekends, every band its{" "}
                {FORMAT_MIX.commercialPerBand} commercial and {FORMAT_MIX.campusPerBand} campus
                nights, every pairing inside a house meets once, and no band plays two weekends
                running more often than the rotation forces. Bands and houses are shown by slot —
                H2·B3 is the third band signed by the second house in that zone.
              </p>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                <span className="font-semibold text-white">What it is not.</span> A booked calendar.
                Commercial nights are spread evenly across a zone&apos;s hub cities, with the
                surplus rotating between bands so nobody is permanently handed the smaller market.
                Campus nights show as {CAMPUS_VENUE_LABEL} because the campus is chosen per band and
                locked later. Real dates still have to survive venue availability, travel, college
                terms, regional holidays and broadcast clashes. {IPL_WINDOW.caveat} Treat this as the shape the booking team is
                solving against — the{" "}
                <Link to="/season" className="text-primary-glow font-semibold hover:underline">
                  season page
                </Link>{" "}
                carries the constraints behind it.
              </p>
            </div>
          </div>
          )}
        </div>
      </div>
    </PageShell>
  );
}
