/**
 * The full 2027 fixture calendar, day by day.
 *
 * Every event is generated by `buildFullSchedule()` from the season structure,
 * so the page cannot drift from the capacity engine — and it says so, by
 * showing whether the generated schedule still reconciles with what the
 * structure requires.
 */

import { createFileRoute, Link } from "@tanstack/react-router";
import { PageShell } from "@/components/layout/PageShell";
import { useState, useMemo } from "react";
import {
  CalendarDays,
  Filter,
  CheckCircle2,
  AlertTriangle,
  Radio,
  Info,
  RotateCcw,
  MapPin,
} from "lucide-react";
import {
  FULL_SCHEDULE,
  SCHEDULE_TOTALS,
  SEASON_CALENDAR,
  NATIONAL_ZONES,
  TOTAL_BANDS,
  TOTAL_HOUSES,
  COMPETITION_WEEKENDS,
  IPL_WINDOW,
  SLOTS,
  type EventKind,
  type ScheduledEvent,
} from "@/data/national-season";
import {
  POST_SEASON,
  POST_SEASON_TOTALS,
  POST_STAGES,
  CLOSING_BLOCKS,
  LADDER,
  QUALIFIERS_PER_ZONE,
} from "@/data/post-season";

export const Route = createFileRoute("/calendar")({
  head: () => ({
    meta: [
      { title: "2027 Fixture Calendar — Kalakshetra" },
      {
        name: "description",
        content:
          "The complete 2027 regular season, day by day: every fixture across all five regional leagues from 22 January to 13 June, filterable by zone, house, band and night type.",
      },
    ],
  }),
  component: CalendarPage,
});

const KIND_META: Record<EventKind, { label: string; chip: string; dot: string }> = {
  commercial: {
    label: "Commercial",
    chip: "border-emerald-500/40 bg-emerald-500/10 text-emerald-300",
    dot: "bg-emerald-400",
  },
  campus: {
    label: "Campus",
    chip: "border-cyan-500/40 bg-cyan-500/10 text-cyan-300",
    dot: "bg-cyan-400",
  },
  cross: {
    label: "Cross night",
    chip: "border-amber-500/40 bg-amber-500/10 text-amber-300",
    dot: "bg-amber-400",
  },
};

const MONTHS = ["all", "Jan", "Feb", "Mar", "Apr", "May", "Jun"];

function Select({
  label,
  value,
  options,
  onChange,
}: {
  label: string;
  value: string;
  options: { id: string; label: string }[];
  onChange: (v: string) => void;
}) {
  return (
    <div className="space-y-1 min-w-0">
      <label className="text-[10px] uppercase tracking-wider font-bold text-muted-foreground">
        {label}
      </label>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        aria-label={label}
        className="w-full rounded-md border border-border bg-background/70 px-2 py-1.5 text-xs font-semibold text-white focus:border-primary/60 focus:outline-none cursor-pointer"
      >
        {options.map((o) => (
          <option key={o.id} value={o.id} className="bg-background text-white">
            {o.label}
          </option>
        ))}
      </select>
    </div>
  );
}

/**
 * July to December. Nobody is named — every side is a slot, so the bracket
 * describes how a band arrives at a night without inventing who won it.
 */
function ChampionshipView({
  stage,
  setStage,
}: {
  stage: string;
  setStage: (v: string) => void;
}) {
  const filtered = useMemo(
    () => (stage === "all" ? POST_SEASON : POST_SEASON.filter((e) => e.stage === stage)),
    [stage],
  );

  const grouped = useMemo(() => {
    const byWeekend = new Map<string, typeof POST_SEASON>();
    filtered.forEach((e) => {
      if (!byWeekend.has(e.weekendLabel)) byWeekend.set(e.weekendLabel, []);
      byWeekend.get(e.weekendLabel)!.push(e);
    });
    return [...byWeekend.entries()];
  }, [filtered]);

  return (
    <div className="space-y-6">
      <div className="bpl-card p-4 border border-primary/25 bg-primary/5 flex gap-3">
        <Info size={15} className="text-primary-glow shrink-0 mt-0.5" />
        <p className="text-[11px] text-muted-foreground leading-relaxed">
          <span className="font-semibold text-white">Nobody is named here, on purpose.</span> Every
          side is a slot — <span className="text-white">AP/TS #3</span>,{" "}
          <span className="text-white">Group B winner</span>,{" "}
          <span className="text-white">QF2 winner</span>,{" "}
          <span className="text-white">Rank 2</span>. The bracket says how a band arrives at a night,
          never who it is. Putting invented names against dated fixtures would publish a fabricated
          result for real acts.
        </p>
      </div>

      {/* Ladder */}
      <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6">
        {LADDER.map((l, i) => (
          <div
            key={l.stage}
            className={`rounded-lg border p-3 ${
              i === LADDER.length - 1
                ? "border-rose-500/40 bg-rose-500/5"
                : "border-border/60 bg-surface/40"
            }`}
          >
            <p className="text-2xl font-display font-extrabold text-primary-glow tabular-nums">
              {l.bands}
            </p>
            <p className="text-[10px] font-bold text-white uppercase tracking-wider mt-0.5">
              {l.stage}
            </p>
            <p className="text-[10px] text-muted-foreground leading-snug mt-1">{l.note}</p>
          </div>
        ))}
      </div>

      {/* Stage filter */}
      <div className="rounded-xl border border-border bg-surface/30 p-3 space-y-2">
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-[10px] uppercase tracking-wider font-bold text-primary-glow flex items-center gap-1.5">
            <Filter size={12} /> Stage
          </span>
          <span className="text-[11px] text-muted-foreground">
            {filtered.length} of {POST_SEASON_TOTALS.events} nights
          </span>
        </div>
        <div className="flex flex-wrap gap-1.5">
          {[
            { id: "all", name: "All stages" },
            ...POST_STAGES.map((st) => ({ id: st.id as string, name: st.name })),
          ].map((st) => (
            <button
              key={st.id}
              type="button"
              onClick={() => setStage(st.id)}
              className={`px-2.5 py-1 rounded-full border text-[11px] font-bold transition cursor-pointer ${
                stage === st.id
                  ? "border-primary/60 bg-primary/15 text-primary-glow"
                  : "border-border bg-secondary/40 text-muted-foreground hover:text-white"
              }`}
            >
              {st.name}
            </button>
          ))}
        </div>
      </div>

      {/* Stage explainers */}
      {stage === "all" && (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {POST_STAGES.map((st) => (
            <div key={st.id} className="rounded-lg border border-border/60 bg-surface/40 p-3">
              <div className="flex items-center gap-2">
                <span
                  className={`text-[9px] uppercase tracking-wider font-bold px-2 py-0.5 rounded-full border ${st.accent}`}
                >
                  {st.window}
                </span>
              </div>
              <p className="text-xs font-bold text-white mt-1.5">{st.name}</p>
              <p className="text-[10px] text-muted-foreground leading-relaxed mt-1">{st.detail}</p>
            </div>
          ))}
        </div>
      )}

      {/* Fixtures */}
      <div className="space-y-3">
        {grouped.map(([weekendLabel, evts]) => (
          <div key={weekendLabel} className="bpl-card border border-border bg-surface/30 overflow-hidden">
            <div className="flex flex-wrap items-center gap-2 px-4 py-2.5 border-b border-border/60 bg-secondary/20">
              <span className="text-xs font-bold text-white">Weekend of {weekendLabel}</span>
              <div className="flex-1" />
              <span className="text-[10px] text-muted-foreground tabular-nums">
                {evts.length} {evts.length === 1 ? "night" : "nights"}
              </span>
            </div>
            <div className="grid gap-1.5 sm:grid-cols-2 lg:grid-cols-3 p-3">
              {evts.map((e) => {
                const meta = POST_STAGES.find((st) => st.id === e.stage)!;
                return (
                  <div
                    key={e.id}
                    className="rounded-md border border-border/50 bg-surface/40 px-2.5 py-2 space-y-1"
                  >
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-[11px] font-semibold text-white leading-snug">
                        {e.sideA} <span className="text-muted-foreground">v</span> {e.sideB}
                      </p>
                      <span
                        className={`text-[8px] uppercase tracking-wider font-bold px-1.5 py-0.5 rounded border shrink-0 ${meta.accent}`}
                      >
                        {meta.name}
                      </span>
                    </div>
                    <p className="text-[10px] text-muted-foreground flex flex-wrap items-center gap-x-1.5">
                      <span>{e.dateLabel}</span>
                      <span className="opacity-40">·</span>
                      <span className="inline-flex items-center gap-0.5">
                        <MapPin size={8} />
                        {e.city}
                      </span>
                    </p>
                    <p className="text-[10px] text-muted-foreground/80 leading-snug">{e.context}</p>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Nov + Dec */}
      <div className="grid gap-4 lg:grid-cols-2">
        {CLOSING_BLOCKS.map((b) => (
          <div key={b.title} className="bpl-card p-5 border border-border bg-surface/40 space-y-3">
            <div>
              <span className="text-[10px] uppercase tracking-wider font-bold text-muted-foreground">
                {b.window}
              </span>
              <h3 className="text-sm font-bold text-white">{b.title}</h3>
            </div>
            <p className="text-[11px] text-muted-foreground leading-relaxed">{b.detail}</p>
            <ul className="space-y-1">
              {b.items.map((it) => (
                <li key={it} className="text-[10px] text-muted-foreground leading-snug flex gap-1.5">
                  <span className="opacity-50">·</span>
                  {it}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      <div
        className={`bpl-card p-4 border flex gap-3 ${
          POST_SEASON_TOTALS.reconciles
            ? "border-emerald-500/30 bg-emerald-500/5"
            : "border-rose-500/30 bg-rose-500/5"
        }`}
      >
        {POST_SEASON_TOTALS.reconciles ? (
          <CheckCircle2 size={15} className="text-emerald-400 shrink-0 mt-0.5" />
        ) : (
          <AlertTriangle size={15} className="text-rose-400 shrink-0 mt-0.5" />
        )}
        <p className="text-[11px] text-muted-foreground leading-relaxed">
          <span className="font-semibold text-emerald-200">Bracket checks out.</span>{" "}
          {POST_SEASON_TOTALS.regionalFinals} regional-final nights (five zones, every one of the{" "}
          {QUALIFIERS_PER_ZONE} qualifiers meeting the other four),{" "}
          {POST_SEASON_TOTALS.groupStage} group nights and {POST_SEASON_TOTALS.knockout} knockout
          nights — {POST_SEASON_TOTALS.events} in all, July to October. November and December carry
          no fixtures by design.
        </p>
      </div>
    </div>
  );
}

function CalendarPage() {
  const [half, setHalf] = useState<"regular" | "championship">("regular");
  const [stage, setStage] = useState<string>("all");
  const [zone, setZone] = useState("all");
  const [house, setHouse] = useState("all");
  const [band, setBand] = useState("all");
  const [kind, setKind] = useState("all");
  const [month, setMonth] = useState("all");

  const zoneMeta = NATIONAL_ZONES.find((z) => z.slug === zone) ?? null;
  const maxHouses = zoneMeta ? zoneMeta.houses : Math.max(...NATIONAL_ZONES.map((z) => z.houses));
  const maxBands = zoneMeta
    ? zoneMeta.bandsPerHouse
    : Math.max(...NATIONAL_ZONES.map((z) => z.bandsPerHouse));

  const filtered = useMemo(
    () =>
      FULL_SCHEDULE.filter((e) => {
        if (zone !== "all" && e.zoneSlug !== zone) return false;
        if (house !== "all" && e.houseNumber !== Number(house)) return false;
        if (band !== "all" && !e.bands.includes(Number(band))) return false;
        if (kind !== "all" && e.kind !== kind) return false;
        if (month !== "all" && !e.dateLabel.includes(month)) return false;
        return true;
      }),
    [zone, house, band, kind, month],
  );

  // Group by weekend, then by calendar day inside it.
  const grouped = useMemo(() => {
    const byWeekend = new Map<number, Map<string, ScheduledEvent[]>>();
    filtered.forEach((e) => {
      if (!byWeekend.has(e.weekendIndex)) byWeekend.set(e.weekendIndex, new Map());
      const days = byWeekend.get(e.weekendIndex)!;
      if (!days.has(e.dateLabel)) days.set(e.dateLabel, []);
      days.get(e.dateLabel)!.push(e);
    });
    return [...byWeekend.entries()].sort((a, b) => a[0] - b[0]);
  }, [filtered]);

  const isDefault =
    zone === "all" && house === "all" && band === "all" && kind === "all" && month === "all";

  const reset = () => {
    setZone("all");
    setHouse("all");
    setBand("all");
    setKind("all");
    setMonth("all");
  };

  return (
    <PageShell>
      <div className="bg-background text-white min-h-screen">
        {/* HERO */}
        <section className="relative overflow-hidden border-b border-border">
          <div
            className="absolute inset-0 pointer-events-none"
            style={{
              background:
                "radial-gradient(ellipse 80% 50% at 50% -20%, rgba(16, 185, 129, 0.16), transparent 70%)",
            }}
          />
          <div className="relative mx-auto max-w-7xl px-4 sm:px-6 pt-16 pb-10 space-y-6 text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-emerald-500/30 bg-emerald-500/10 text-emerald-300 text-xs font-semibold">
              <CalendarDays size={14} />
              <span>Season 1 · 2027 Regular Season</span>
            </div>
            <h1 className="text-4xl sm:text-5xl font-display font-extrabold tracking-tight text-white max-w-3xl mx-auto leading-tight">
              Every night of <span className="gradient-text">2027</span>
            </h1>
            <p className="text-sm text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              The complete regular season, 22 January to 13 June — all{" "}
              {SCHEDULE_TOTALS.events} events across {NATIONAL_ZONES.length} regional leagues,{" "}
              {TOTAL_HOUSES} production houses and {TOTAL_BANDS} bands, generated from the season
              structure rather than typed out.
            </p>

            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 pt-2 text-left">
              {[
                { v: SCHEDULE_TOTALS.events, l: "Events", h: `${COMPETITION_WEEKENDS} weekends` },
                { v: SCHEDULE_TOTALS.commercial, l: "Commercial", h: "5 per band" },
                { v: SCHEDULE_TOTALS.campus, l: "Campus", h: "3 per band" },
                { v: SCHEDULE_TOTALS.cross, l: "Cross nights", h: "Shared stages" },
              ].map((s) => (
                <div key={s.l} className="bpl-card p-4 border border-border/80 bg-surface/60">
                  <p className="text-2xl font-display font-extrabold text-emerald-300 tabular-nums">
                    {s.v}
                  </p>
                  <p className="text-[10px] uppercase tracking-wider font-bold text-white mt-1">
                    {s.l}
                  </p>
                  <p className="text-[10px] text-muted-foreground">{s.h}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <div className="mx-auto max-w-7xl px-4 sm:px-6 py-10 space-y-6">
          {/* Reconciliation */}
          <div
            className={`bpl-card p-4 border flex gap-3 ${
              SCHEDULE_TOTALS.reconciles
                ? "border-emerald-500/30 bg-emerald-500/5"
                : "border-rose-500/30 bg-rose-500/5"
            }`}
          >
            {SCHEDULE_TOTALS.reconciles ? (
              <CheckCircle2 size={15} className="text-emerald-400 shrink-0 mt-0.5" />
            ) : (
              <AlertTriangle size={15} className="text-rose-400 shrink-0 mt-0.5" />
            )}
            <p className="text-[11px] text-muted-foreground leading-relaxed">
              {SCHEDULE_TOTALS.reconciles ? (
                <>
                  <span className="font-semibold text-emerald-200">Schedule reconciles.</span> The{" "}
                  {SCHEDULE_TOTALS.individual} individual fixtures and {SCHEDULE_TOTALS.cross} cross
                  nights generated here match exactly what the{" "}
                  <Link to="/season" className="text-primary-glow font-semibold hover:underline">
                    capacity engine
                  </Link>{" "}
                  says the structure requires. Every band gets 5 commercial and 3 campus nights;
                  cross nights follow house size, so AP/TS bands get three and the rest get one.
                </>
              ) : (
                <span className="font-semibold text-rose-200">
                  Generated schedule does not match the structural requirement — the generator and
                  the capacity engine disagree.
                </span>
              )}
            </p>
          </div>

          {/* Half-year toggle */}
          <div className="flex flex-wrap gap-2">
            {(
              [
                { id: "regular", label: "Regular Season · Jan–Jun", n: SCHEDULE_TOTALS.events },
                { id: "championship", label: "Championship · Jul–Dec", n: POST_SEASON_TOTALS.events },
              ] as const
            ).map((h) => (
              <button
                key={h.id}
                type="button"
                onClick={() => setHalf(h.id)}
                className={`px-4 py-2 rounded-lg border text-xs font-bold transition cursor-pointer ${
                  half === h.id
                    ? "border-primary/60 bg-primary/15 text-primary-glow"
                    : "border-border bg-secondary/40 text-muted-foreground hover:text-white hover:border-primary/40"
                }`}
              >
                {h.label}
                <span className="ml-2 opacity-70 tabular-nums">{h.n}</span>
              </button>
            ))}
          </div>

          {half === "championship" ? (
            <ChampionshipView stage={stage} setStage={setStage} />
          ) : (
            <>
          {/* Filters */}
          <div className="rounded-xl border border-primary/25 bg-primary/5 p-3 space-y-3">
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-[10px] uppercase tracking-wider font-bold text-primary-glow flex items-center gap-1.5">
                <Filter size={12} /> Filter
              </span>
              <span className="text-[11px] text-muted-foreground">
                {filtered.length} of {SCHEDULE_TOTALS.events} events
              </span>
              <div className="flex-1" />
              {!isDefault && (
                <button
                  type="button"
                  onClick={reset}
                  className="inline-flex items-center gap-1 text-[11px] font-semibold text-muted-foreground hover:text-white transition cursor-pointer"
                >
                  <RotateCcw size={11} /> Reset
                </button>
              )}
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-2">
              <Select
                label="Zone"
                value={zone}
                options={[
                  { id: "all", label: "All zones" },
                  ...NATIONAL_ZONES.map((z) => ({ id: z.slug, label: z.shortName })),
                ]}
                onChange={(v) => {
                  setZone(v);
                  setHouse("all");
                  setBand("all");
                }}
              />
              <Select
                label="House"
                value={house}
                options={[
                  { id: "all", label: "All houses" },
                  ...Array.from({ length: maxHouses }, (_, i) => ({
                    id: String(i + 1),
                    label: `House ${i + 1}`,
                  })),
                ]}
                onChange={setHouse}
              />
              <Select
                label="Band"
                value={band}
                options={[
                  { id: "all", label: "All bands" },
                  ...Array.from({ length: maxBands }, (_, i) => ({
                    id: String(i + 1),
                    label: `Band ${i + 1}`,
                  })),
                ]}
                onChange={setBand}
              />
              <Select
                label="Night type"
                value={kind}
                options={[
                  { id: "all", label: "All nights" },
                  { id: "commercial", label: "Commercial" },
                  { id: "campus", label: "Campus" },
                  { id: "cross", label: "Cross night" },
                ]}
                onChange={setKind}
              />
              <Select
                label="Month"
                value={month}
                options={MONTHS.map((m) => ({ id: m, label: m === "all" ? "All months" : m }))}
                onChange={setMonth}
              />
            </div>
            <div className="flex flex-wrap gap-3 pt-1">
              {(Object.keys(KIND_META) as EventKind[]).map((k) => (
                <span key={k} className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
                  <span className={`h-2 w-2 rounded-full ${KIND_META[k].dot}`} />
                  {KIND_META[k].label}
                </span>
              ))}
              <span className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
                <Radio size={10} className="text-amber-400" /> Cricket-window weekend
              </span>
            </div>
          </div>

          {/* Weekend-by-weekend schedule */}
          {grouped.length === 0 ? (
            <div className="bpl-card p-8 border border-border bg-surface/30 text-center">
              <p className="text-sm text-muted-foreground">
                No fixtures match this filter. A two-band zone has no Band 3 or Band 4.
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {grouped.map(([weekendIndex, days]) => {
                const weekend = SEASON_CALENDAR.find((w) => w.index === weekendIndex);
                const count = [...days.values()].reduce((s, d) => s + d.length, 0);
                return (
                  <div
                    key={weekendIndex}
                    className="bpl-card border border-border bg-surface/30 overflow-hidden"
                  >
                    <div className="flex flex-wrap items-center gap-2 px-4 py-2.5 border-b border-border/60 bg-secondary/20">
                      <span className="text-[10px] uppercase tracking-wider font-bold px-2 py-0.5 rounded-full border border-primary/40 bg-primary/10 text-primary-glow">
                        Weekend {weekend?.number}
                      </span>
                      <span className="text-xs font-bold text-white">{weekend?.label}</span>
                      {weekend?.iplOverlap && (
                        <span className="inline-flex items-center gap-1 text-[9px] uppercase tracking-wider font-bold text-amber-400">
                          <Radio size={9} /> Cricket window
                        </span>
                      )}
                      <div className="flex-1" />
                      <span className="text-[10px] text-muted-foreground tabular-nums">
                        {count} {count === 1 ? "event" : "events"}
                      </span>
                    </div>

                    <div className="divide-y divide-border/40">
                      {[...days.entries()].map(([dayLabel, dayEvents]) => (
                        <div key={dayLabel} className="px-4 py-3">
                          <p className="text-[11px] font-bold text-white mb-2">{dayLabel}</p>
                          <div className="grid gap-1.5 sm:grid-cols-2 lg:grid-cols-3">
                            {dayEvents
                              .slice()
                              .sort(
                                (a, b) =>
                                  SLOTS.findIndex((s) => s.label === a.slot) -
                                  SLOTS.findIndex((s) => s.label === b.slot),
                              )
                              .map((e) => (
                                <div
                                  key={e.id}
                                  className="flex items-start gap-2 rounded-md border border-border/50 bg-surface/40 px-2.5 py-2"
                                >
                                  <span
                                    className={`h-2 w-2 rounded-full shrink-0 mt-1.5 ${KIND_META[e.kind].dot}`}
                                  />
                                  <div className="min-w-0 flex-1">
                                    <p className="text-[11px] font-semibold text-white leading-snug">
                                      {e.zoneName} · H{e.houseNumber} ·{" "}
                                      {e.bands.map((b) => `B${b}`).join(" v ")}
                                    </p>
                                    <p className="text-[10px] text-muted-foreground flex flex-wrap items-center gap-x-1.5">
                                      <span>{e.slot}</span>
                                      <span className="opacity-40">·</span>
                                      <span className="inline-flex items-center gap-0.5">
                                        <MapPin size={8} />
                                        {e.city}
                                      </span>
                                    </p>
                                  </div>
                                  <span
                                    className={`text-[8px] uppercase tracking-wider font-bold px-1.5 py-0.5 rounded border shrink-0 ${KIND_META[e.kind].chip}`}
                                  >
                                    {KIND_META[e.kind].label}
                                  </span>
                                </div>
                              ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          )}

            </>
          )}

          {/* Footnote — describes the regular-season list only */}
          {half === "regular" && (
          <div className="bpl-card p-5 border border-border bg-surface/30 flex gap-3">
            <Info size={15} className="text-primary-glow shrink-0 mt-0.5" />
            <div className="space-y-2">
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                <span className="font-semibold text-white">What this is.</span> A structurally valid
                schedule: every house gets its eight weekends, every band its five commercial and
                three campus nights, every pairing inside a house meets once, and no band plays two
                weekends running more often than the rotation forces. Bands and houses are shown by
                slot — H2·B3 is the third band signed by the second house in that zone.
              </p>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                <span className="font-semibold text-white">What it is not.</span> A booked calendar.
                Cities rotate in proportion to each hub&apos;s share of its zone, but real dates have
                to survive venue availability, travel, college terms, regional holidays and
                broadcast clashes. {IPL_WINDOW.caveat} Treat this as the shape the booking team is
                solving against — the{" "}
                <Link to="/season" className="text-primary-glow font-semibold hover:underline">
                  season page
                </Link>{" "}
                carries the constraints behind it.
              </p>
            </div>
          </div>
          )}
        </div>
      </div>
    </PageShell>
  );
}
