/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as ProductionHousesRouteImport } from './routes/production-houses'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EconomicsRouteImport } from './routes/economics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BandsRouteImport } from './routes/bands'
import { Route as BandCultureRouteImport } from './routes/band-culture'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueIndexRouteImport } from './routes/league/index'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as LeagueZoneRouteImport } from './routes/league/$zone'
import { Route as JoinVolunteerRouteImport } from './routes/join/volunteer'
import { Route as JoinVenueRouteImport } from './routes/join/venue'
import { Route as JoinSponsorRouteImport } from './routes/join/sponsor'
import { Route as JoinProductionHouseRouteImport } from './routes/join/production-house'
import { Route as JoinInfluencerRouteImport } from './routes/join/influencer'
import { Route as JoinEventManagerRouteImport } from './routes/join/event-manager'
import { Route as JoinBandRouteImport } from './routes/join/band'
import { Route as BandsBandIdRouteImport } from './routes/bands/$bandId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionHousesRoute = ProductionHousesRouteImport.update({
  id: '/production-houses',
  path: '/production-houses',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsRoute = EconomicsRouteImport.update({
  id: '/economics',
  path: '/economics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BandsRoute = BandsRouteImport.update({
  id: '/bands',
  path: '/bands',
  getParentRoute: () => rootRouteImport,
} as any)
const BandCultureRoute = BandCultureRouteImport.update({
  id: '/band-culture',
  path: '/band-culture',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueIndexRoute = LeagueIndexRouteImport.update({
  id: '/league/',
  path: '/league/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueZoneRoute = LeagueZoneRouteImport.update({
  id: '/league/$zone',
  path: '/league/$zone',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinVolunteerRoute = JoinVolunteerRouteImport.update({
  id: '/join/volunteer',
  path: '/join/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinVenueRoute = JoinVenueRouteImport.update({
  id: '/join/venue',
  path: '/join/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinSponsorRoute = JoinSponsorRouteImport.update({
  id: '/join/sponsor',
  path: '/join/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinProductionHouseRoute = JoinProductionHouseRouteImport.update({
  id: '/join/production-house',
  path: '/join/production-house',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInfluencerRoute = JoinInfluencerRouteImport.update({
  id: '/join/influencer',
  path: '/join/influencer',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinEventManagerRoute = JoinEventManagerRouteImport.update({
  id: '/join/event-manager',
  path: '/join/event-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinBandRoute = JoinBandRouteImport.update({
  id: '/join/band',
  path: '/join/band',
  getParentRoute: () => rootRouteImport,
} as any)
const BandsBandIdRoute = BandsBandIdRouteImport.update({
  id: '/$bandId',
  path: '/$bandId',
  getParentRoute: () => BandsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/band-culture': typeof BandCultureRoute
  '/bands': typeof BandsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/economics': typeof EconomicsRoute
  '/events': typeof EventsRoute
  '/handbook': typeof HandbookRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/production-houses': typeof ProductionHousesRoute
  '/season': typeof SeasonRoute
  '/signup': typeof SignupRoute
  '/venues': typeof VenuesRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bands/$bandId': typeof BandsBandIdRoute
  '/join/band': typeof JoinBandRoute
  '/join/event-manager': typeof JoinEventManagerRoute
  '/join/influencer': typeof JoinInfluencerRoute
  '/join/production-house': typeof JoinProductionHouseRoute
  '/join/sponsor': typeof JoinSponsorRoute
  '/join/venue': typeof JoinVenueRoute
  '/join/volunteer': typeof JoinVolunteerRoute
  '/league/$zone': typeof LeagueZoneRoute
  '/join/': typeof JoinIndexRoute
  '/league/': typeof LeagueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/band-culture': typeof BandCultureRoute
  '/bands': typeof BandsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/economics': typeof EconomicsRoute
  '/events': typeof EventsRoute
  '/handbook': typeof HandbookRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/production-houses': typeof ProductionHousesRoute
  '/season': typeof SeasonRoute
  '/signup': typeof SignupRoute
  '/venues': typeof VenuesRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bands/$bandId': typeof BandsBandIdRoute
  '/join/band': typeof JoinBandRoute
  '/join/event-manager': typeof JoinEventManagerRoute
  '/join/influencer': typeof JoinInfluencerRoute
  '/join/production-house': typeof JoinProductionHouseRoute
  '/join/sponsor': typeof JoinSponsorRoute
  '/join/venue': typeof JoinVenueRoute
  '/join/volunteer': typeof JoinVolunteerRoute
  '/league/$zone': typeof LeagueZoneRoute
  '/join': typeof JoinIndexRoute
  '/league': typeof LeagueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/band-culture': typeof BandCultureRoute
  '/bands': typeof BandsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/economics': typeof EconomicsRoute
  '/events': typeof EventsRoute
  '/handbook': typeof HandbookRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/production-houses': typeof ProductionHousesRoute
  '/season': typeof SeasonRoute
  '/signup': typeof SignupRoute
  '/venues': typeof VenuesRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bands/$bandId': typeof BandsBandIdRoute
  '/join/band': typeof JoinBandRoute
  '/join/event-manager': typeof JoinEventManagerRoute
  '/join/influencer': typeof JoinInfluencerRoute
  '/join/production-house': typeof JoinProductionHouseRoute
  '/join/sponsor': typeof JoinSponsorRoute
  '/join/venue': typeof JoinVenueRoute
  '/join/volunteer': typeof JoinVolunteerRoute
  '/league/$zone': typeof LeagueZoneRoute
  '/join/': typeof JoinIndexRoute
  '/league/': typeof LeagueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/band-culture'
    | '/bands'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/economics'
    | '/events'
    | '/handbook'
    | '/login'
    | '/media'
    | '/onboarding'
    | '/partners'
    | '/production-houses'
    | '/season'
    | '/signup'
    | '/venues'
    | '/admin/applications'
    | '/auth/callback'
    | '/bands/$bandId'
    | '/join/band'
    | '/join/event-manager'
    | '/join/influencer'
    | '/join/production-house'
    | '/join/sponsor'
    | '/join/venue'
    | '/join/volunteer'
    | '/league/$zone'
    | '/join/'
    | '/league/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/band-culture'
    | '/bands'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/economics'
    | '/events'
    | '/handbook'
    | '/login'
    | '/media'
    | '/onboarding'
    | '/partners'
    | '/production-houses'
    | '/season'
    | '/signup'
    | '/venues'
    | '/admin/applications'
    | '/auth/callback'
    | '/bands/$bandId'
    | '/join/band'
    | '/join/event-manager'
    | '/join/influencer'
    | '/join/production-house'
    | '/join/sponsor'
    | '/join/venue'
    | '/join/volunteer'
    | '/league/$zone'
    | '/join'
    | '/league'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/band-culture'
    | '/bands'
    | '/calendar'
    | '/community'
    | '/dashboard'
    | '/economics'
    | '/events'
    | '/handbook'
    | '/login'
    | '/media'
    | '/onboarding'
    | '/partners'
    | '/production-houses'
    | '/season'
    | '/signup'
    | '/venues'
    | '/admin/applications'
    | '/auth/callback'
    | '/bands/$bandId'
    | '/join/band'
    | '/join/event-manager'
    | '/join/influencer'
    | '/join/production-house'
    | '/join/sponsor'
    | '/join/venue'
    | '/join/volunteer'
    | '/league/$zone'
    | '/join/'
    | '/league/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BandCultureRoute: typeof BandCultureRoute
  BandsRoute: typeof BandsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  EconomicsRoute: typeof EconomicsRoute
  EventsRoute: typeof EventsRoute
  HandbookRoute: typeof HandbookRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  ProductionHousesRoute: typeof ProductionHousesRoute
  SeasonRoute: typeof SeasonRoute
  SignupRoute: typeof SignupRoute
  VenuesRoute: typeof VenuesRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  JoinBandRoute: typeof JoinBandRoute
  JoinEventManagerRoute: typeof JoinEventManagerRoute
  JoinInfluencerRoute: typeof JoinInfluencerRoute
  JoinProductionHouseRoute: typeof JoinProductionHouseRoute
  JoinSponsorRoute: typeof JoinSponsorRoute
  JoinVenueRoute: typeof JoinVenueRoute
  JoinVolunteerRoute: typeof JoinVolunteerRoute
  LeagueZoneRoute: typeof LeagueZoneRoute
  JoinIndexRoute: typeof JoinIndexRoute
  LeagueIndexRoute: typeof LeagueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-houses': {
      id: '/production-houses'
      path: '/production-houses'
      fullPath: '/production-houses'
      preLoaderRoute: typeof ProductionHousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics': {
      id: '/economics'
      path: '/economics'
      fullPath: '/economics'
      preLoaderRoute: typeof EconomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bands': {
      id: '/bands'
      path: '/bands'
      fullPath: '/bands'
      preLoaderRoute: typeof BandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band-culture': {
      id: '/band-culture'
      path: '/band-culture'
      fullPath: '/band-culture'
      preLoaderRoute: typeof BandCultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/': {
      id: '/league/'
      path: '/league'
      fullPath: '/league/'
      preLoaderRoute: typeof LeagueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$zone': {
      id: '/league/$zone'
      path: '/league/$zone'
      fullPath: '/league/$zone'
      preLoaderRoute: typeof LeagueZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/volunteer': {
      id: '/join/volunteer'
      path: '/join/volunteer'
      fullPath: '/join/volunteer'
      preLoaderRoute: typeof JoinVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/venue': {
      id: '/join/venue'
      path: '/join/venue'
      fullPath: '/join/venue'
      preLoaderRoute: typeof JoinVenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/sponsor': {
      id: '/join/sponsor'
      path: '/join/sponsor'
      fullPath: '/join/sponsor'
      preLoaderRoute: typeof JoinSponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/production-house': {
      id: '/join/production-house'
      path: '/join/production-house'
      fullPath: '/join/production-house'
      preLoaderRoute: typeof JoinProductionHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/influencer': {
      id: '/join/influencer'
      path: '/join/influencer'
      fullPath: '/join/influencer'
      preLoaderRoute: typeof JoinInfluencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/event-manager': {
      id: '/join/event-manager'
      path: '/join/event-manager'
      fullPath: '/join/event-manager'
      preLoaderRoute: typeof JoinEventManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/band': {
      id: '/join/band'
      path: '/join/band'
      fullPath: '/join/band'
      preLoaderRoute: typeof JoinBandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bands/$bandId': {
      id: '/bands/$bandId'
      path: '/$bandId'
      fullPath: '/bands/$bandId'
      preLoaderRoute: typeof BandsBandIdRouteImport
      parentRoute: typeof BandsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BandsRouteChildren {
  BandsBandIdRoute: typeof BandsBandIdRoute
}

const BandsRouteChildren: BandsRouteChildren = {
  BandsBandIdRoute: BandsBandIdRoute,
}

const BandsRouteWithChildren = BandsRoute._addFileChildren(BandsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  BandCultureRoute: BandCultureRoute,
  BandsRoute: BandsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  EconomicsRoute: EconomicsRoute,
  EventsRoute: EventsRoute,
  HandbookRoute: HandbookRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  ProductionHousesRoute: ProductionHousesRoute,
  SeasonRoute: SeasonRoute,
  SignupRoute: SignupRoute,
  VenuesRoute: VenuesRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  JoinBandRoute: JoinBandRoute,
  JoinEventManagerRoute: JoinEventManagerRoute,
  JoinInfluencerRoute: JoinInfluencerRoute,
  JoinProductionHouseRoute: JoinProductionHouseRoute,
  JoinSponsorRoute: JoinSponsorRoute,
  JoinVenueRoute: JoinVenueRoute,
  JoinVolunteerRoute: JoinVolunteerRoute,
  LeagueZoneRoute: LeagueZoneRoute,
  JoinIndexRoute: JoinIndexRoute,
  LeagueIndexRoute: LeagueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
